# Generated by Django 3.2.4 on 2022-03-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerswithfiles',
            name='customer_fingerprint',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='customerswithfiles',
            name='customer_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerswithfiles',
            name='customer_photo',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='customerswithfiles',
            name='customer_recording',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='customerswithfiles',
            name='customer_signature',
            field=models.FileField(upload_to='media/'),
        ),
    ]
