# Generated by Django 3.2.4 on 2022-03-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220309_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
